### ISSUE TITLE
Program crashes on non ASCII characters.

### ISSUE THREAD

**Issue by bootldrDNB** [svbnet/RedSea#2]
I am trying to rip an album, with Estonian characters.

And get this error.

> Traceback (most recent call last):
>   File "redsea.py", line 113, in <module>
>     main()
>   File "redsea.py", line 101, in main
>     md.download_media(track, config['tidal']['quality'], media_info)
>   File "/mnt/p/RedSea/mediadownloader.py", line 130, in download_media
>     temp_file = self._dl_url(stream_data['url'], track_path)
>   File "/mnt/p/RedSea/mediadownloader.py", line 31, in _dl_url
>     with open(where, 'wb') as f:
> UnicodeEncodeError: 'ascii' codec can't encode character '\xf5' in position 24: ordinal not in range(128)

**Comment by svbnet** [comment]
Try installing the UTF-8 locale for your system:

```
sudo locale-gen "en_US.UTF-8"
```
If that doesn't work, you can also try this (on a Debian/dpkg-based system):

```
sudo dpkg-reconfigure locales
```

**Comment by bootldrDNB** [comment]
I got the same error after doing that. :(

**Comment by svbnet** [comment]
Unfortunately Linux isn't my forte (I use Windows as my main OS). I did get the same error on my VM but I was able to fix it with the technique above. A solution is to add a command line switch to disable outputting of tracks as they're being downloaded but that would require time I just don't have. You're welcome to post a solution or submit a pull request, though, if you have any ideas.
